### ISSUE TITLE
Minor bug from cv2 due to min-max normalization

### ISSUE THREAD

**Issue by dpaysan** [GVS-Lab/chrometrics#1]
Unfortunately cv2 does not ensure that the float values when performing min-max scaling are actually within the defined integer range. This might cause problems later on when e.g. computing the texture features. A small hacky fix would be adding:

` # normalize images`
`raw_image = cv.normalize(
        raw_image, None, alpha=0, beta=255, norm_type=cv.NORM_MINMAX, dtype=cv.CV_32F
    )`
    `raw_image[raw_image < 0] = 0.0`
   ` raw_image[raw_image > 255] = 255.0`
    in the script Run_feature_extraction.py .

**Comment by SaradhaVenkatachalapathy** [comment]
Thanks for bringing this up! 

I have actually removed (commented) the min-max scaling as it is not necessary for extracting NMCO features. The user can add in any preprocessing required for their specific image set. 

Closing this issue.
